[log]
level = "info" # debug, info, warn, error

# Global Providers
[[providers]]
name = "gemini"

# Projects Configuration
[[projects]]
name = "jarvis"

[projects.agent]
type = "antigravity"
provider_refs = ["antigravity"]

[projects.agent.options]
work_dir = "/root/agent"
mode = "yolo"
# model = "gemini-2.5-flash"
cmd = "agy" 
# timeout_mins = 30

# Platforms bound to the project
[[projects.platforms]]
type = "line"

[projects.platforms.options]
channel_secret = "${LINE_CHANNEL_SECRET}"
channel_token = "${LINE_CHANNEL_ACCESS_TOKEN}"
port = "8080"
callback_path = "/message"
allow_from = "*"
